import os

PROJECT_NAME = "${DOMAIN_FQDN}"
PROJECT_ROOT = os.path.abspath( os.path.dirname(os.path.dirname(__file__)) )
PROJECT_URL = "http://%s" % PROJECT_NAME
SERVER_ROOT = os.path.abspath( os.path.normpath(os.path.dirname(PROJECT_ROOT) ) )

DJANGO_DATABASE_TYPE = "${DJANGO_DATABASE_TYPE}"
DJANGO_DATABASE_NAME = ${DJANGO_DATABASE_NAME}
DJANGO_DATABASE_USERNAME = "${DJANGO_DATABASE_USERNAME}"
DJANGO_DATABASE_PASSWORD = "${DJANGO_DATABASE_PASSWORD}"
DJANGO_DATABASE_HOST = "${DJANGO_DATABASE_HOST}"
DJANGO_DATABASE_PORT = "${DJANGO_DATABASE_PORT}"

