DOMAIN_FQDN = "${DOMAIN_FQDN}"
DJANGO_DATABASE_TYPE = "${DJANGO_DATABASE_TYPE}"
DJANGO_DATABASE_NAME = "${DJANGO_DATABASE_NAME}"
DJANGO_DATABASE_USERNAME = "${DJANGO_DATABASE_USERNAME}"
DJANGO_DATABASE_PASSWORD = "${DJANGO_DATABASE_PASSWORD}"
DJANGO_DATABASE_HOST = "${DJANGO_DATABASE_HOST}"
DJANGO_DATABASE_PORT = "${DJANGO_DATABASE_PORT}"

